name       : ispc
version    : 1.16.0
release    : 6
source     :
    - https://github.com/ispc/ispc/archive/refs/tags/v1.16.0.tar.gz : c6b1c5487ce0e6b439e7cdf6656179092204a4256f99615485f0569b72dc74b0
license    : BSD-3-Clause
component  : programming
summary    : Intel SPMD Program Compiler
description: |
    ispc is a compiler for a variant of the C programming language, with extensions for single program, multiple data programming. Under the SPMD model, the programmer writes a program that generally appears to be a regular serial program, though the execution model is actually that a number of program instances execute in parallel on the hardware.
clang      : yes
setup      : |
    %apply_patches
    %cmake_ninja \
      -DARM_ENABLED=OFF \
      -DISPC_NO_DUMPS=ON \
      -DISPC_INCLUDE_EXAMPLES=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
