name       : ispc
version    : 1.19.0
release    : 9
source     :
    - git|https://github.com/ispc/ispc.git : v1.19.0
license    : BSD-3-Clause
component  : programming
summary    : Intel SPMD Program Compiler
description: |
    ispc is a compiler for a variant of the C programming language, with extensions for single program, multiple data programming. Under the SPMD model, the programmer writes a program that generally appears to be a regular serial program, though the execution model is actually that a number of program instances execute in parallel on the hardware.
clang      : yes
builddeps  :
    - pkgconfig(LLVMSPIRVLib)
    - pkgconfig(libze_loader)
    - vc-intrinsics
setup      : |
    %cmake_ninja \
      -DARM_ENABLED=OFF \
      -DISPC_NO_DUMPS=ON \
      -DISPC_INCLUDE_EXAMPLES=OFF \
      -DISPC_OPAQUE_PTR_MODE=OFF \
      -DXE_ENABLED=ON \
      -DXE_DEPS_DIR=/usr
build      : |
    %ninja_build
install    : |
    %ninja_install
    # ???
    rm -fr $installdir/home
