name       : ispc
version    : 0.18.0
release    : 7
source     :
    - https://github.com/ispc/ispc/archive/refs/tags/v1.18.0.tar.gz : 81f2cc23b555c815faf53429e9eee37d1f2f16873ae7074e382ede94721ee042
license    : BSD-3-Clause
component  : programming
summary    : Intel SPMD Program Compiler
description: |
    ispc is a compiler for a variant of the C programming language, with extensions for single program, multiple data programming. Under the SPMD model, the programmer writes a program that generally appears to be a regular serial program, though the execution model is actually that a number of program instances execute in parallel on the hardware.
clang      : yes
setup      : |
    %cmake_ninja \
      -DARM_ENABLED=OFF \
      -DISPC_NO_DUMPS=ON \
      -DISPC_INCLUDE_EXAMPLES=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
