name       : ispc
version    : 1.14.1
release    : 1
source     :
    - https://github.com/ispc/ispc/archive/v1.14.1.tar.gz : 3a7ee9ab90b9e9932b7b4effc9bb3ef45ca271d60d9ec6bc8c335242b5ec097b
license    : BSD-3-Clause
component  : programming
summary    : Intel SPMD Program Compiler
description: |
    ispc is a compiler for a variant of the C programming language, with extensions for single program, multiple data programming. Under the SPMD model, the programmer writes a program that generally appears to be a regular serial program, though the execution model is actually that a number of program instances execute in parallel on the hardware.
clang      : yes
setup      : |
    %patch -p1 < $pkgfiles/0001-strip-out-legacy-libtinfo.patch
    %cmake_ninja \
      -DARM_ENABLED=OFF \
      -DISPC_NO_DUMPS=ON \
      -DISPC_INCLUDE_EXAMPLES=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
